name: Java CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Build WAR
      run: mvn clean package

    - name: Upload WAR
      uses: actions/upload-artifact@v3
      with:
        name: eBook-war
        path: target/*.war